name: Release Charts

on:
  push:
    branches:
      - main
    paths:
      - 'charts/**'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write  
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Package and Push
        run: |
          mkdir -p .cr-release-packages
          helm package charts/cockroachdb -d .cr-release-packages/
          git checkout gh-pages
          mv .cr-release-packages/*.tgz .
          helm repo index . --url https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}
          git add .
          git commit -m "Release chart"
          git push origin gh-pages

env:
  CR_TOKEN: "${{ github.token }}"